/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppOrgListRouteRouteImport } from './routes/app/_org-list/route'
import { Route as AppSlugRouteRouteImport } from './routes/app/$slug/route'
import { Route as AppOrgListIndexRouteImport } from './routes/app/_org-list/index'
import { Route as AppOrgListInvitationsRouteImport } from './routes/app/_org-list/invitations'
import { Route as AppSlugSettingsRouteImport } from './routes/app/$slug/settings'
import { Route as AppSlugSettingsIndexRouteImport } from './routes/app/$slug/settings.index'
import { Route as AppSlugItemsIndexRouteImport } from './routes/app/$slug/_items/index'
import { Route as AppSlugSettingsInvitationsRouteImport } from './routes/app/$slug/settings.invitations'
import { Route as AppSlugItemsIdRouteImport } from './routes/app/$slug/_items/$id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppOrgListRouteRoute = AppOrgListRouteRouteImport.update({
  id: '/app/_org-list',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlugRouteRoute = AppSlugRouteRouteImport.update({
  id: '/app/$slug',
  path: '/app/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgListIndexRoute = AppOrgListIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgListRouteRoute,
} as any)
const AppOrgListInvitationsRoute = AppOrgListInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppOrgListRouteRoute,
} as any)
const AppSlugSettingsRoute = AppSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppSlugRouteRoute,
} as any)
const AppSlugSettingsIndexRoute = AppSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSlugSettingsRoute,
} as any)
const AppSlugItemsIndexRoute = AppSlugItemsIndexRouteImport.update({
  id: '/_items/',
  path: '/',
  getParentRoute: () => AppSlugRouteRoute,
} as any)
const AppSlugSettingsInvitationsRoute =
  AppSlugSettingsInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AppSlugSettingsRoute,
  } as any)
const AppSlugItemsIdRoute = AppSlugItemsIdRouteImport.update({
  id: '/_items/$id',
  path: '/$id',
  getParentRoute: () => AppSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/$slug': typeof AppSlugRouteRouteWithChildren
  '/app': typeof AppOrgListRouteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/app/$slug/settings': typeof AppSlugSettingsRouteWithChildren
  '/app/invitations': typeof AppOrgListInvitationsRoute
  '/app/': typeof AppOrgListIndexRoute
  '/app/$slug/$id': typeof AppSlugItemsIdRoute
  '/app/$slug/settings/invitations': typeof AppSlugSettingsInvitationsRoute
  '/app/$slug/': typeof AppSlugItemsIndexRoute
  '/app/$slug/settings/': typeof AppSlugSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/app/invitations': typeof AppOrgListInvitationsRoute
  '/app': typeof AppOrgListIndexRoute
  '/app/$slug/$id': typeof AppSlugItemsIdRoute
  '/app/$slug/settings/invitations': typeof AppSlugSettingsInvitationsRoute
  '/app/$slug': typeof AppSlugItemsIndexRoute
  '/app/$slug/settings': typeof AppSlugSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/app/$slug': typeof AppSlugRouteRouteWithChildren
  '/app/_org-list': typeof AppOrgListRouteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/app/$slug/settings': typeof AppSlugSettingsRouteWithChildren
  '/app/_org-list/invitations': typeof AppOrgListInvitationsRoute
  '/app/_org-list/': typeof AppOrgListIndexRoute
  '/app/$slug/_items/$id': typeof AppSlugItemsIdRoute
  '/app/$slug/settings/invitations': typeof AppSlugSettingsInvitationsRoute
  '/app/$slug/_items/': typeof AppSlugItemsIndexRoute
  '/app/$slug/settings/': typeof AppSlugSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/$slug'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/app/$slug/settings'
    | '/app/invitations'
    | '/app/'
    | '/app/$slug/$id'
    | '/app/$slug/settings/invitations'
    | '/app/$slug/'
    | '/app/$slug/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/app/invitations'
    | '/app'
    | '/app/$slug/$id'
    | '/app/$slug/settings/invitations'
    | '/app/$slug'
    | '/app/$slug/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app/$slug'
    | '/app/_org-list'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/app/$slug/settings'
    | '/app/_org-list/invitations'
    | '/app/_org-list/'
    | '/app/$slug/_items/$id'
    | '/app/$slug/settings/invitations'
    | '/app/$slug/_items/'
    | '/app/$slug/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AppSlugRouteRoute: typeof AppSlugRouteRouteWithChildren
  AppOrgListRouteRoute: typeof AppOrgListRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/_org-list': {
      id: '/app/_org-list'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppOrgListRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$slug': {
      id: '/app/$slug'
      path: '/app/$slug'
      fullPath: '/app/$slug'
      preLoaderRoute: typeof AppSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_org-list/': {
      id: '/app/_org-list/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppOrgListIndexRouteImport
      parentRoute: typeof AppOrgListRouteRoute
    }
    '/app/_org-list/invitations': {
      id: '/app/_org-list/invitations'
      path: '/invitations'
      fullPath: '/app/invitations'
      preLoaderRoute: typeof AppOrgListInvitationsRouteImport
      parentRoute: typeof AppOrgListRouteRoute
    }
    '/app/$slug/settings': {
      id: '/app/$slug/settings'
      path: '/settings'
      fullPath: '/app/$slug/settings'
      preLoaderRoute: typeof AppSlugSettingsRouteImport
      parentRoute: typeof AppSlugRouteRoute
    }
    '/app/$slug/settings/': {
      id: '/app/$slug/settings/'
      path: '/'
      fullPath: '/app/$slug/settings/'
      preLoaderRoute: typeof AppSlugSettingsIndexRouteImport
      parentRoute: typeof AppSlugSettingsRoute
    }
    '/app/$slug/_items/': {
      id: '/app/$slug/_items/'
      path: '/'
      fullPath: '/app/$slug/'
      preLoaderRoute: typeof AppSlugItemsIndexRouteImport
      parentRoute: typeof AppSlugRouteRoute
    }
    '/app/$slug/settings/invitations': {
      id: '/app/$slug/settings/invitations'
      path: '/invitations'
      fullPath: '/app/$slug/settings/invitations'
      preLoaderRoute: typeof AppSlugSettingsInvitationsRouteImport
      parentRoute: typeof AppSlugSettingsRoute
    }
    '/app/$slug/_items/$id': {
      id: '/app/$slug/_items/$id'
      path: '/$id'
      fullPath: '/app/$slug/$id'
      preLoaderRoute: typeof AppSlugItemsIdRouteImport
      parentRoute: typeof AppSlugRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AppSlugSettingsRouteChildren {
  AppSlugSettingsInvitationsRoute: typeof AppSlugSettingsInvitationsRoute
  AppSlugSettingsIndexRoute: typeof AppSlugSettingsIndexRoute
}

const AppSlugSettingsRouteChildren: AppSlugSettingsRouteChildren = {
  AppSlugSettingsInvitationsRoute: AppSlugSettingsInvitationsRoute,
  AppSlugSettingsIndexRoute: AppSlugSettingsIndexRoute,
}

const AppSlugSettingsRouteWithChildren = AppSlugSettingsRoute._addFileChildren(
  AppSlugSettingsRouteChildren,
)

interface AppSlugRouteRouteChildren {
  AppSlugSettingsRoute: typeof AppSlugSettingsRouteWithChildren
  AppSlugItemsIdRoute: typeof AppSlugItemsIdRoute
  AppSlugItemsIndexRoute: typeof AppSlugItemsIndexRoute
}

const AppSlugRouteRouteChildren: AppSlugRouteRouteChildren = {
  AppSlugSettingsRoute: AppSlugSettingsRouteWithChildren,
  AppSlugItemsIdRoute: AppSlugItemsIdRoute,
  AppSlugItemsIndexRoute: AppSlugItemsIndexRoute,
}

const AppSlugRouteRouteWithChildren = AppSlugRouteRoute._addFileChildren(
  AppSlugRouteRouteChildren,
)

interface AppOrgListRouteRouteChildren {
  AppOrgListInvitationsRoute: typeof AppOrgListInvitationsRoute
  AppOrgListIndexRoute: typeof AppOrgListIndexRoute
}

const AppOrgListRouteRouteChildren: AppOrgListRouteRouteChildren = {
  AppOrgListInvitationsRoute: AppOrgListInvitationsRoute,
  AppOrgListIndexRoute: AppOrgListIndexRoute,
}

const AppOrgListRouteRouteWithChildren = AppOrgListRouteRoute._addFileChildren(
  AppOrgListRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AppSlugRouteRoute: AppSlugRouteRouteWithChildren,
  AppOrgListRouteRoute: AppOrgListRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
